id: AC4590EF0
title: 'Song and Dance to Delight the Ḍākas and Ḍākinīs: An Aspiration for the Sixfold
  Satisfaction of the Maṇḍala of the Feast-Gathering'
type: translation
pechas:
- IBBBA65CC
- IBCF207F4
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:38:12.812275
  last_modified_at: 2023-01-04 12:38:12.812280
  collections:
  - Jamyang Khyentse Wangpo Series
  - Works of Tibetan Masters
alignment_to_base:
  IBBBA65CC/1745: '9811'
  IBCF207F4/9AA5: '9811'
